apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
spec:
  selector:
    app: {{ .Values.metadata.name }}
  ports:
  - name: http
    port: {{ .Values.svc.port }}
    targetPort: {{ .Values.env.containerPort }}
    nodePort: {{ .Values.svc.nodeport }}
  type: {{ .Values.svc.type }}
  