version: 2.1

# executors:
#   docker-publisher:
#     # environment:
#     #   IMAGE_TAG: <username>/helloworld:latest
#     docker:
#       - image: docker:stable

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py3-pip python3
            pip install \
              docker-compose requests
      - restore_cache:
          keys: 
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            cd app
            docker build --cache-from=$IMAGE -f Dockerfile -t $IMAGE .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar $IMAGE
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Run tests
          command: |
            cd ./app
            docker-compose up -d && sleep 5
            python3 unit.py
      - deploy:
          name: Push application Docker image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" — password-stdin
            docker push $IMAGE:latest
            docker push $IMAGE:$CIRCLE_SHA1

