version: 2.1
orbs:
  discord: antonioned/discord@0.1.0
# executors:
#   docker-publisher:
#     # environment:
#     #   IMAGE_TAG: <username>/helloworld:latest
#     docker:
#       - image: docker:stable

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py3-pip python3
            pip3 install \
              docker-compose==1.12.0 requests
      - restore_cache:
          keys: 
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            cd app
            docker build --cache-from=$IMAGE -f Dockerfile -t $IMAGE .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar $IMAGE
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Run tests
          command: |
            cd ./app
            echo $IMAGE
            docker-compose up -d && sleep 5
            docker exec app_weather_1 python3 /app/unit.py
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p $DOCKERHUB_PASSWORD
            docker push $IMAGE:latest
            docker tag $IMAGE $IMAGE:$CIRCLE_SHA1
            docker push $IMAGE:$CIRCLE_SHA1
      - discord/status:
          fail_only: true
          failure_message: "Triggered by: **${CIRCLE_USERNAME}** \\n\\n Ooops! The **$CIRCLE_JOB** job has failed!"
          webhook: "${DISCORD_WEBHOOK}"
