version: '3'

services:
  weather:
    image: katieg123/weather-jsondb:5
    environment:
      - API_KEY=${API_KEY}
      - BIND_PORT=58080
      - LOG_LEVEL=DEBUG
      - BG_COLOR=${BG_COLOR}
      # - API_KEY_OPENAI=${API_KEY_OPENAI}
      # - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      # - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

    networks:
      - weather-app
    deploy:
      replicas: 1
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:rw
      - ./app/certs:/etc/nginx/certs:ro
    ports:
      - 443:443
      - 80:80
    networks:
      - weather-app
    depends_on:
    - weather


networks:
  weather-app:
    external: true