version: '3'

services:
  weather:
    image: test/test
    environment:
      - API_KEY=${API_KEY}
      - BIND_PORT=8080
      - LOG_LEVEL=DEBUG
    ports:
      - 8080:8080
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   volumes:
  #     - ./nginx/:/etc/nginx/conf.d/:rw
  #     - ./app/certs:/etc/nginx/certs:ro
  #   ports:
  #     - 443:443
  #     - 80:80
  #   networks:
  #     - weather-app
  #   depends_on:
  #   - weather


# networks:
#   weather-app:
#     external: true