apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos
  namespace: deploy
spec:
  destination:
    name: ''
    namespace: deploy
    server: 'https://kubernetes.default.svc'
  source:
    path: chaos
    repoURL: 'https://github.com/katieg12345/argo'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=orphan